let data = [
  {
    nombre: "TABLA DE ASADO SMALL",
    medida: "24x40x2cm",
    producto: "tabla",
    precio: 1700,
    image: "tabla-de-asado-small.JPG",
  },
  {
    nombre: "TABLA DE ASADO LARGE",
    medida: "28x55x2cm",
    producto: "tabla",
    precio: 3000,
    image: "tabla-de-asado-large.JPG",
  },
  {
    nombre: "TABLA DE ASADO XL LARGE",
    medida: "28x55x4cm",
    producto: "tabla",
    precio: 4650,
    image: "tabla-de-asado-xl-large.JPG",
  },
  {
    nombre: "TABLA DE ASADO CON AGUJERO",
    medida: "24x40x2cm",
    producto: "tabla",
    precio: 1700,
    image: "tabla-de-asado-agujero.JPG",
  },
  {
    nombre: "TABLA CON MANGO ",
    medida: "21x40x2cm",
    producto: "tabla",
    precio: 2100,
    image: "tabla-con-mango.JPG",
  },
  {
    nombre: "BANDEJA SMALL",
    medida: "24x40x2cm",
    producto: "bandeja",
    precio: 2300,
    image: "bandeja-small.JPG",
  },
  {
    nombre: "BANDEJA XL LARGE",
    medida: "28x55x4cm",
    producto: "bandeja",
    precio: 6300,
    image: "bandeja-xl-large.JPG",
  },
  {
    nombre: "TABLA DE PICADA",
    medida: "19x38x2cm",
    producto: "tabla",
    precio: 1800,
    image: "tabla-de-picada.JPG",
  },
  {
    nombre: "BANDEJA DE PICADA",
    medida: "19x35x2cm",
    producto: "bandeja",
    precio: 1950,
    image: "bandeja-de-picada.JPG",
  },
  {
    nombre: "PLATO DE ASADO",
    medida: "19x35x2cm",
    producto: "plato",
    precio: 1200,
    image: "plato-de-asado.JPG",
  },
  {
    nombre: "PLATO DE SUSHI LAQUEADO",
    medida: "14x23x2cm",
    producto: "plato",
    precio: 1100,
    image: "plato-de-sushi.JPG",
  },
  {
    nombre: "ORDENADOR DE ESCRITORIO",
    medida: "14x30x4cm",
    producto: "ordenado de escritorio",
    precio: 2400,
    image: "ordenador-de-escritorio.JPG",
  },
  {
    nombre: "CAJA NESPRESSO",
    medida: "30x40cm",
    producto: "caja nespresso",
    precio: 5500,
    image: "caja-nespresso.JPG",
  },
];

export default data;
